/**
 * UWC — серверные конвертеры SQL dump ↔ CSV / JSON (фаза 2, уровень B).
 *
 * Чистый JS, без внешних зависимостей. Поддерживает:
 *   - CREATE TABLE (столбцы, типы)
 *   - INSERT INTO ... VALUES(...),  (...),  ...  (много строк)
 *   - UPDATE, DELETE (игнорируются — это ж не dump-to-json)
 *
 * SQL → JSON: { "table_name": [ {col: val, ...}, ... ], ... }
 * JSON → SQL: CREATE TABLE + INSERT.
 *
 * ЭТО dump ↔ формат, а не SQLite .db файл ↔ формат — SQLite требует sql.js
 * (GPL) или better-sqlite3 (GPL), которых мы не используем.
 */

/** MIME для SQL dump. */
export const SQL_MIME = 'text/plain'

/** Типы SQLite: text, integer, real, blob, numeric. */
// Зарезервировано: проверка типов колонок при более строгом парсинге типов
const _SQLITE_TYPES = new Set(['TEXT', 'INTEGER', 'REAL', 'BLOB', 'NUMERIC', 'VARCHAR', 'CHAR', 'BOOLEAN'])

/**
 * SQL dump (string) → JSON (string).
 *
 * Парсим CREATE TABLE для схемы, INSERT для данных.
 * Возвращаем { "table": [ {col: val, ...}, ... ], "table2": [...] }.
 */
export function sqlToJson(input: string): string {
  const tables: Record<string, Record<string, unknown>[]> = {}
  const schemas: Record<string, string[]> = {} // table → column names (ordered)

  // --- CREATE TABLE: захватываем имя таблицы и имена колонок ---
  // CREATE TABLE [имя] (col1 TYPE, col2 TYPE, ...)
  const createRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:`?["[]?)?(\w+)(?:`?["\]]?)?\s*\(([\s\S]*?)\)\s*(?:;|\\n|$)/gi
  let m: RegExpExecArray | null
  while ((m = createRe.exec(input)) !== null) {
    const tableName = m[1]!
    const colsStr = m[2]!
    const cols = parseColumns(colsStr)
    schemas[tableName] = cols
    if (!tables[tableName]) tables[tableName] = []
  }

  // --- INSERT INTO: VALUES (...) ---
  // INSERT INTO table (col1, col2) VALUES (val1, val2), (val3, val4);
  // INSERT INTO table VALUES (val1, val2), (val3, val4);
  const insertRe = /INSERT\s+INTO\s+(?:`?["[]?)?(\w+)(?:`?["\]]?)?\s*(?:\(([^)]*)\))?\s*VALUES\s*([\s\S]*?);?(?=\nINSERT|\nCREATE|\nUPDATE|\nDELETE|$)/gi
  while ((m = insertRe.exec(input)) !== null) {
    const tableName = m[1]!
    const colsStr = m[2] // может быть undefined → используем схему
    const valuesStr = m[3]!

    const cols = colsStr ? parseColumnList(colsStr) : (schemas[tableName] || [])

    if (!tables[tableName]) tables[tableName] = []

    // разбираем VALUES ( ... ), ( ... )
    const rowRegex = /\(([^)]*)\)/g
    let rowMatch: RegExpExecArray | null
    while ((rowMatch = rowRegex.exec(valuesStr)) !== null) {
      const vals = parseValues(rowMatch[1]!)
      const row: Record<string, unknown> = {}
      cols.forEach((col, i) => {
        row[col] = vals[i] !== undefined ? vals[i] : null
      })
      tables[tableName].push(row)
    }
  }

  return JSON.stringify(tables, null, 2)
}

/**
 * JSON (string) → SQL dump (string).
 *
 * Поддерживает: { "table": [ {col: val}, ... ] } или [[...], ...] (только первая таблица).
 */
export function jsonToSql(input: string): string {
  const parsed = JSON.parse(input) as unknown
  const tables: Record<string, Record<string, unknown>[]> = {}

  if (Array.isArray(parsed)) {
    tables['table1'] = parsed as Record<string, unknown>[]
  } else if (typeof parsed === 'object' && parsed !== null) {
    Object.assign(tables, parsed as Record<string, Record<string, unknown>[]>)
  } else {
    throw new Error('errors.badJson')
  }

  const lines: string[] = []
  for (const [tableName, rows] of Object.entries(tables)) {
    if (rows.length === 0) {
      lines.push(`CREATE TABLE ${tableName} (id integer);`)
      lines.push('')
      continue
    }

    // определяем колонки по первому объекту
    const cols = Object.keys(rows[0]!)
    const colDefs = cols.map((c) => {
      const sample = rows[0]![c]
      const type = inferSqlType(sample)
      return `  ${c} ${type} NOT NULL DEFAULT ''`
    })

    lines.push(`CREATE TABLE ${tableName} (`)
    lines.push(colDefs.join(',\n'))
    lines.push(');')
    lines.push('')

    // INSERT
    for (const row of rows) {
      const vals = cols.map((c) => sqlValue(row[c]))
      lines.push(`INSERT INTO ${tableName} (${cols.map(sqlIdent).join(', ')}) VALUES (${vals.join(', ')});`)
    }
    lines.push('')
  }

  lines.push('/* auto-generated by UWC — http://localhost:3000 */')
  return lines.join('\n')
}

/** Парсим определения колонок из CREATE TABLE (col TYPE, col2 TYPE, ...). */
function parseColumns(colsStr: string): string[] {
  const result: string[] = []
  // простой split по запятой, но учитываем вложенные скобки (PRIMARY KEY, UNIQUE, ...)
  let depth = 0
  let cur = ''
  for (const ch of colsStr) {
    if (ch === '(') depth++
    else if (ch === ')') depth--
    if (ch === ',' && depth === 0) {
      const name = cur.trim().split(/\s+/)[0]?.replace(/[`"\\]\r\n]/g, '').trim()
      if (name && !name.toUpperCase().startsWith('PRIMARY') && !name.toUpperCase().startsWith('FOREIGN') && !name.toUpperCase().startsWith('UNIQUE') && !name.toUpperCase().startsWith('CHECK')) {
        result.push(name)
      }
      cur = ''
    } else cur += ch
  }
  const name = cur.trim().split(/\s+/)[0]?.replace(/[`"\\]\r\n]/g, '').trim()
  if (name && !name.toUpperCase().startsWith('PRIMARY') && !name.toUpperCase().startsWith('FOREIGN') && !name.toUpperCase().startsWith('UNIQUE') && !name.toUpperCase().startsWith('CHECK')) {
    result.push(name)
  }
  return result.filter(Boolean)
}

/** Парсим список колонок в INSERT INTO (col1, col2, col3). */
function parseColumnList(colsStr: string): string[] {
  return colsStr.split(',').map((c) => c.trim().replace(/[`"\\]\r\n]/g, '').trim()).filter(Boolean)
}

/** Парсим значения внутри (...) → массив typed значений. */
function parseValues(valsStr: string): unknown[] {
  const result: unknown[] = []
  let cur = ''
  let inStr = false
  let strQuote: string | null = null
  let depth = 0

  for (let i = 0; i < valsStr.length; i++) {
    const ch = valsStr[i]!
    if (inStr) {
      if (ch === strQuote) {
        // проверяем экранированную кавычку ''
        if (valsStr[i + 1] === strQuote) {
          cur += ch; i++
        } else {
          inStr = false; cur += ch
        }
      } else cur += ch
    } else if (ch === "'" || ch === '"') {
      inStr = true; strQuote = ch; cur += ch
    } else if (ch === '(') depth++
    else if (ch === ')') depth--
    else if (ch === ',' && depth === 0) {
      result.push(sqlLiteralToJs(cur.trim()))
      cur = ''
    } else {
      cur += ch
    }
  }
  if (cur.trim() || result.length === 0) {
    result.push(sqlLiteralToJs(cur.trim()))
  }
  return result
}

/** SQL literal → JS value. */
function sqlLiteralToJs(s: string): unknown {
  if (s === '' || s === 'NULL') return null
  if (s.startsWith("'") && s.endsWith("'")) return s.slice(1, -1).replace(/''/g, "'")
  if (s.startsWith('"')) return s.slice(1, -1).replace(/""/g, '"')
  if (s.startsWith('x') || s.startsWith('X')) {
    // HEX blob: x'...' или X'...'
    return s
  }
  if (/^-?\d+$/.test(s)) return Number(s)
  if (/^-?\d+\.\d+$/.test(s) || /^-?\d+e\d+$/i.test(s)) return Number(s)
  if (/^(true|false)$/.test(s)) return s === 'true'
  return s
}

/** JS значение → SQL literal. */
function sqlValue(v: unknown): string {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'number') {
    if (Number.isInteger(v)) return String(v)
    return String(v)
  }
  if (typeof v === 'boolean') return v ? '1' : '0'
  if (v instanceof Date) return `'${v.toISOString().replace(/T/, ' ').replace(/\..+/, '')}'`
  // строка: экранируем одинарные кавычки
  return `'${String(v).replace(/'/g, "''")}'`
}

/** Infer SQL тип по JS значению для CREATE TABLE. */
function inferSqlType(v: unknown): string {
  if (v === null || v === undefined) return 'TEXT'
  if (typeof v === 'number') return Number.isInteger(v) ? 'INTEGER' : 'REAL'
  if (typeof v === 'boolean') return 'INTEGER'
  if (v instanceof Date) return 'TEXT'
  if (typeof v === 'string') return 'TEXT'
  return 'TEXT'
}

/** Экранируем имя колонки/таблицы. */
function sqlIdent(name: string): string {
  if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) return name
  return `"${name.replace(/"/g, '""')}"`
}
